### ISSUE TITLE
Architecture can connect to ESD Oracle

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#434]

**Comment by acozine** [comment]
Currently the oracle database that contains the fields exported from ESD is behind an Emory firewall. So I need to install the utilities and gems that allow a connection to oracle databases in general, and also to figure out how the connection to the machine that hosts this particular oracle database will work.

**Comment by acozine** [comment]
Using https://github.com/cbandy/travis-oracle as a platform to enable testing of the oracle connection.

**Comment by acozine** [comment]
Code in the `oracle_esb` branch deploys correctly to both machines now and passes on travis, so if we need an oracle connection, we can write tests for it. Other modifications we would need for an oracle connection to Emory include opening ports on AWS and adding a section to `/opt/laevigata/shared/config/database.yml`.

**Comment by acozine** [comment]
For tips on using the read-only databases, see https://stackoverflow.com/questions/16533393/efficient-way-to-pull-data-from-second-database

**Comment by acozine** [comment]
New entry in `database.yml` would look something like this:
```
production_esd:
  adapter: oracle_enhanced
  host: extra-db.emory.edu
  database: jdbc:oracle:thin:@extra-db.emory.edu:[PORT]:dbname
  username: # add username here
  password: # add password here
```
